name: Organization-Level Security Findings

on:
  push:

jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PowerBI_PAT }}" | gh auth login --with-token

      - name: Export Organization-Level Security Findings
        run: |
          # Create output directory
          mkdir -p ./org-security-export

          # Export Code Scanning Alerts
          gh api -H "Accept: application/vnd.github+json" \
            "/orgs/${{ github.repository_owner }}/code-scanning/alerts" \
            --paginate > ./org-security-export/code_scanning_alerts.json

          # Export Dependabot Alerts
          gh api -H "Accept: application/vnd.github+json" \
            "/orgs/${{ github.repository_owner }}/dependabot/alerts" \
            --paginate > ./org-security-export/dependabot_alerts.json

          # Convert JSON to CSV using jq
          jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[$keys[]]])[] | @csv' \
            ./org-security-export/code_scanning_alerts.json > ./org-security-export/code_scanning_alerts.csv

          jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[$keys[]]])[] | @csv' \
            ./org-security-export/dependabot_alerts.json > ./org-security-export/dependabot_alerts.csv

      - name: Upload Security Findings
        uses: actions/upload-artifact@v4
        with:
          name: org-security-findings
          path: ./org-security-export/*.csv
          retention-days: 30

      - name: Optional - Print Summary
        run: |
          echo "Code Scanning Alerts:"
          wc -l ./org-security-export/code_scanning_alerts.csv
          echo "Dependabot Alerts:"
          wc -l ./org-security-export/dependabot_alerts.csv
