name: Org-level GitHub Advanced Security Data to CSV
on:
   push:

jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export GHAS Data for Organization
        uses: advanced-security/ghas-to-csv@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          org-level: true  # Specify org-level export
          output-path: ./ghas-org-export

      - name: List generated CSV files
        run: ls -l ./ghas-org-export/*.csv

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: org-ghas-security-data
          path: ./ghas-org-export/*.csv
          retention-days: 30

      - name: Optional - Send CSV to external storage
        # Uncomment and configure as needed for additional storage/reporting
        # uses: your-preferred-storage-action@v1
        # with:
        #   files: ./ghas-org-export/*.csv
