name: Export GitHub Advanced Security Data to CSV
on:
  push:
jobs:
  export-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run GitHub Advanced Security to CSV
        uses: advanced-security/ghas-to-csv@v3
        env:
          GITHUB_PAT: ${{ secrets.PAT }}  # Ensure you have stored your PAT in the repository secrets
      - name: Upload CSV
        uses: actions/upload-artifact@v2
        with:
          name: ghas-data
          path: '*.csv'
