name: Build a war file for my Java Webapo
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install -f pom.xml

    - name: List files in target directory
      run: ls -l target/ 
   
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

    - name: Upload Maven artifact
      uses: actions/upload-artifact@v4
      with:
          name: web_application
          path: MyWebApp.war

    - name: Login to Azure
      uses: azure/login@v1
      with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            auth-type: 'SERVICE_PRINCIPAL'

    - name: Get the latest WAR file
      id: latest_war
      run: |
          # Find the most recent JAR file in the target directory
          LATEST_WAR=$(ls -t target/*.war | head -n 1)
          echo "LATEST_WAR=$LATEST_WAR" >> $GITHUB_ENV
          # Print out the location to ensure it's found
          echo "WAR file path: $LATEST_WAR"

    - name: Upload the .war file to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: Test04
          package: ${{ env.LATEST_WAR }}
   
    
